# Generated by Django 4.2.23 on 2025-09-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0093_issue_assignee_updated_date_alter_issue_assignee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTrainMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "train_id",
                    models.CharField(
                        help_text="Train event identifier (defaults to task ID)", max_length=100
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[("AC", "Accepted"), ("NA", "Not Applicable"), ("RJ", "Rejected")],
                        default="NA",
                        help_text="Train verdict: AC (Accepted), NA (Not Applicable), RJ (Rejected)",
                        max_length=2,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the train event", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Optional confidence score for the verdict (0.0 to 1.0)",
                        null=True,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        help_text="Associated CVAT task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_metadata",
                        to="engine.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Train Metadata",
                "verbose_name_plural": "Task Train Metadata",
                "db_table": "custom_task_train_metadata",
            },
        ),
    ]
