# Generated by Django 4.2.23 on 2025-09-11 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0093_issue_assignee_updated_date_alter_issue_assignee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField(help_text="Comment content")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="True if comment has been edited after creation"
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("GEN", "General"),
                            ("FB", "Feedback"),
                            ("ISS", "Issue"),
                            ("REV", "Review"),
                            ("NOTE", "Note"),
                            ("Q", "Question"),
                        ],
                        default="GEN",
                        help_text="Comment category for organization",
                        max_length=4,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment if this is a reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="custom.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to="engine.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
                "db_table": "custom_task_comment",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["task", "-created_date"], name="custom_task_task_id_d235e9_idx"
                    ),
                    models.Index(
                        fields=["author", "-created_date"], name="custom_task_author__f8037a_idx"
                    ),
                ],
            },
        ),
    ]
